language: python
sudo: false
dist: trusty
services:
- docker
cache:
  directories:
  - "$HOME/.cache/pip"
_install: &_install
  - pip install --upgrade pip
  - pip install -r requirements.txt --no-binary wmd codecov
  - pip install -e .
_coverage: &_coverage
  - SCRIPT="coverage run -m unittest discover"
matrix:
  include:
    - python: 3.4
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.5
      env: *_coverage
      before_install: *_before_install
      install: *_install
    - python: 3.6
      env: SCRIPT="pep8 --max-line-length=99 ."
      install: pip install pep8
    - python: 3.6
      env: *_coverage
      before_install: *_before_install
      install: *_install
      after_success:
        - codecov
  fast_finish: true
before_script:
- docker run -d --privileged -p 9432:9432 --name bblfshd bblfsh/bblfshd                 
- docker exec -it bblfshd bblfshctl driver install --all
script:
- (eval "$SCRIPT")
notifications:
  email: false
